apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: used-car-price-api
  namespace: used-car-price-api
  labels:
    release: prometheus        
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: used-car-price-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s